services:
  web:
    hostname: 'web'
    container_name: 'web_app'
    image: nginx:stable-alpine
    ports:
      - '4173:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - api
    networks:
      - mynetwork

  app:
    hostname: 'app'
    container_name: 'client-app'
    build: ./client
    # ports:
    #   - '4173:80'
    depends_on:
      - api
    networks:
      - mynetwork

  api:
    hostname: 'api'
    container_name: 'api-server'
    build: ./api
    # ports:
    #   - '3000:3000'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
